// Canonical category taxonomy + default merchant→category rules.
// Shared by the seed, the CSV importer, and the categorization engine so
// everything agrees on the same set.

export type CategorySeed = {
  name: string;
  group: "Income" | "Essentials" | "Lifestyle" | "Financial" | "Other";
  icon: string;
  color: string;
  isIncome?: boolean;
};

// A coherent, high-contrast categorical palette (reused across charts).
export const PALETTE = {
  indigo: "#635BFF",
  emerald: "#16A374",
  amber: "#E5A93A",
  rose: "#E14C60",
  sky: "#2E9BD6",
  violet: "#9B6BFF",
  teal: "#14B8A6",
  orange: "#F5793B",
  pink: "#EC6AA8",
  lime: "#7DB93C",
  cyan: "#22B0C9",
  slate: "#7A879C",
} as const;

export const CATEGORIES: CategorySeed[] = [
  // Income
  { name: "Paycheck", group: "Income", icon: "💼", color: PALETTE.emerald, isIncome: true },
  { name: "Interest & Dividends", group: "Income", icon: "📈", color: PALETTE.teal, isIncome: true },
  { name: "Other Income", group: "Income", icon: "💰", color: PALETTE.lime, isIncome: true },
  // Essentials
  { name: "Rent & Mortgage", group: "Essentials", icon: "🏠", color: PALETTE.indigo },
  { name: "Groceries", group: "Essentials", icon: "🛒", color: PALETTE.emerald },
  { name: "Utilities", group: "Essentials", icon: "💡", color: PALETTE.amber },
  { name: "Transportation", group: "Essentials", icon: "🚗", color: PALETTE.sky },
  { name: "Phone & Internet", group: "Essentials", icon: "📶", color: PALETTE.cyan },
  { name: "Healthcare", group: "Essentials", icon: "⚕️", color: PALETTE.rose },
  { name: "Insurance", group: "Essentials", icon: "🛡️", color: PALETTE.slate },
  // Lifestyle
  { name: "Dining & Takeout", group: "Lifestyle", icon: "🍔", color: PALETTE.orange },
  { name: "Coffee", group: "Lifestyle", icon: "☕", color: PALETTE.amber },
  { name: "Shopping", group: "Lifestyle", icon: "🛍️", color: PALETTE.pink },
  { name: "Entertainment", group: "Lifestyle", icon: "🎬", color: PALETTE.violet },
  { name: "Travel", group: "Lifestyle", icon: "✈️", color: PALETTE.sky },
  { name: "Subscriptions", group: "Lifestyle", icon: "📺", color: PALETTE.pink },
  { name: "Fitness", group: "Lifestyle", icon: "🏋️", color: PALETTE.teal },
  { name: "Personal Care", group: "Lifestyle", icon: "💇", color: PALETTE.violet },
  { name: "Pets", group: "Lifestyle", icon: "🐾", color: PALETTE.lime },
  // Financial
  { name: "Savings Transfer", group: "Financial", icon: "🏦", color: PALETTE.emerald },
  { name: "Investments", group: "Financial", icon: "📊", color: PALETTE.indigo },
  { name: "Loan Payment", group: "Financial", icon: "💳", color: PALETTE.rose },
  { name: "Fees", group: "Financial", icon: "🧾", color: PALETTE.slate },
  { name: "Taxes", group: "Financial", icon: "🏛️", color: PALETTE.slate },
  // Other
  { name: "Gifts & Donations", group: "Other", icon: "🎁", color: PALETTE.pink },
  { name: "Education", group: "Other", icon: "🎓", color: PALETTE.sky },
  { name: "Uncategorized", group: "Other", icon: "❓", color: PALETTE.slate },
];

// Ordered lowest→highest priority is implied by array order (later wins on ties
// only if priority equal; the engine sorts by longest match then priority).
export const DEFAULT_RULES: { matcher: string; category: string }[] = [
  { matcher: "payroll", category: "Paycheck" },
  { matcher: "direct deposit", category: "Paycheck" },
  { matcher: "salary", category: "Paycheck" },
  { matcher: "dividend", category: "Interest & Dividends" },
  { matcher: "interest paid", category: "Interest & Dividends" },
  { matcher: "whole foods", category: "Groceries" },
  { matcher: "trader joe", category: "Groceries" },
  { matcher: "safeway", category: "Groceries" },
  { matcher: "kroger", category: "Groceries" },
  { matcher: "aldi", category: "Groceries" },
  { matcher: "costco", category: "Groceries" },
  { matcher: "grocery", category: "Groceries" },
  { matcher: "starbucks", category: "Coffee" },
  { matcher: "dunkin", category: "Coffee" },
  { matcher: "blue bottle", category: "Coffee" },
  { matcher: "peet", category: "Coffee" },
  { matcher: "coffee", category: "Coffee" },
  { matcher: "mcdonald", category: "Dining & Takeout" },
  { matcher: "chipotle", category: "Dining & Takeout" },
  { matcher: "uber eats", category: "Dining & Takeout" },
  { matcher: "doordash", category: "Dining & Takeout" },
  { matcher: "grubhub", category: "Dining & Takeout" },
  { matcher: "restaurant", category: "Dining & Takeout" },
  { matcher: "pizza", category: "Dining & Takeout" },
  { matcher: "sushi", category: "Dining & Takeout" },
  { matcher: "uber", category: "Transportation" },
  { matcher: "lyft", category: "Transportation" },
  { matcher: "shell", category: "Transportation" },
  { matcher: "chevron", category: "Transportation" },
  { matcher: "exxon", category: "Transportation" },
  { matcher: "parking", category: "Transportation" },
  { matcher: "transit", category: "Transportation" },
  { matcher: "netflix", category: "Subscriptions" },
  { matcher: "spotify", category: "Subscriptions" },
  { matcher: "hulu", category: "Subscriptions" },
  { matcher: "disney", category: "Subscriptions" },
  { matcher: "prime video", category: "Subscriptions" },
  { matcher: "apple.com/bill", category: "Subscriptions" },
  { matcher: "amazon", category: "Shopping" },
  { matcher: "target", category: "Shopping" },
  { matcher: "walmart", category: "Shopping" },
  { matcher: "best buy", category: "Shopping" },
  { matcher: "etsy", category: "Shopping" },
  { matcher: "rent", category: "Rent & Mortgage" },
  { matcher: "mortgage", category: "Rent & Mortgage" },
  { matcher: "landlord", category: "Rent & Mortgage" },
  { matcher: "pg&e", category: "Utilities" },
  { matcher: "electric", category: "Utilities" },
  { matcher: "water bill", category: "Utilities" },
  { matcher: "utility", category: "Utilities" },
  { matcher: "verizon", category: "Phone & Internet" },
  { matcher: "at&t", category: "Phone & Internet" },
  { matcher: "t-mobile", category: "Phone & Internet" },
  { matcher: "comcast", category: "Phone & Internet" },
  { matcher: "xfinity", category: "Phone & Internet" },
  { matcher: "cvs", category: "Healthcare" },
  { matcher: "walgreens", category: "Healthcare" },
  { matcher: "pharmacy", category: "Healthcare" },
  { matcher: "dental", category: "Healthcare" },
  { matcher: "clinic", category: "Healthcare" },
  { matcher: "geico", category: "Insurance" },
  { matcher: "state farm", category: "Insurance" },
  { matcher: "progressive", category: "Insurance" },
  { matcher: "insurance", category: "Insurance" },
  { matcher: "planet fitness", category: "Fitness" },
  { matcher: "equinox", category: "Fitness" },
  { matcher: "peloton", category: "Fitness" },
  { matcher: "gym", category: "Fitness" },
  { matcher: "delta air", category: "Travel" },
  { matcher: "united air", category: "Travel" },
  { matcher: "airbnb", category: "Travel" },
  { matcher: "marriott", category: "Travel" },
  { matcher: "hotel", category: "Travel" },
  { matcher: "expedia", category: "Travel" },
  { matcher: "amc ", category: "Entertainment" },
  { matcher: "cinema", category: "Entertainment" },
  { matcher: "steam", category: "Entertainment" },
  { matcher: "playstation", category: "Entertainment" },
  { matcher: "ticketmaster", category: "Entertainment" },
  { matcher: "vanguard", category: "Investments" },
  { matcher: "fidelity", category: "Investments" },
  { matcher: "robinhood", category: "Investments" },
  { matcher: "coinbase", category: "Investments" },
  { matcher: "schwab", category: "Investments" },
  { matcher: "transfer to savings", category: "Savings Transfer" },
  { matcher: "student loan", category: "Loan Payment" },
  { matcher: "sofi", category: "Loan Payment" },
  { matcher: "loan pmt", category: "Loan Payment" },
  { matcher: "overdraft", category: "Fees" },
  { matcher: "atm fee", category: "Fees" },
  { matcher: "service charge", category: "Fees" },
  { matcher: "irs", category: "Taxes" },
  { matcher: "tax pmt", category: "Taxes" },
  { matcher: "donation", category: "Gifts & Donations" },
  { matcher: "red cross", category: "Gifts & Donations" },
  { matcher: "udemy", category: "Education" },
  { matcher: "coursera", category: "Education" },
  { matcher: "tuition", category: "Education" },
  { matcher: "petco", category: "Pets" },
  { matcher: "petsmart", category: "Pets" },
  { matcher: "chewy", category: "Pets" },
  { matcher: "sephora", category: "Personal Care" },
  { matcher: "ulta", category: "Personal Care" },
  { matcher: "salon", category: "Personal Care" },
  { matcher: "barber", category: "Personal Care" },
];
